config/routes.rb
Rails.application.routes.draw do

  resources :rooms do
    resources :chats, only: [:index, :create]
  end

  devise_for :students, controllers: {
    sessions:      'students/sessions',
    passwords:     'students/passwords',
    registrations: 'students/registrations'
  }

  devise_scope :student do
    get 'students/search', to: 'students#search'
    get 'students/index', to: 'students#index'
    get 'students/:id', to: 'students/registrations#show'
    get 'students/:id/interviews', to: 'students/registrations#interviews'
    get 'student_profile_edit', to: 'students/registrations#student_profile_edit', as: 'student_profile_edit'
    patch 'student_profile_update', to: 'students/registrations#student_profile_update', as: 'student_profile_update'
  end

  devise_for :teachers, controllers: {
    sessions:      'teachers/sessions',
    passwords:     'teachers/passwords',
    registrations: 'teachers/registrations'
  }

  devise_scope :teacher do
    get 'teachers/:id', to: 'teachers/registrations#show'
    patch 'teachers/:id/student_update', to: 'teachers/registrations#student_update'
    get 'teachers/:id/student_details/:id', to: 'teachers/registrations#student_details'
    get 'teachers/:id/student_details/:id/interviews', to: 'teachers/registrations#interviews'
    get 'teachers/:id/teacher_profile_edit', to: 'teachers/registrations#teacher_profile_edit', as: 'teacher_profile_edit'
    patch 'teacher_profile_update', to: 'teachers/registrations#teacher_profile_update', as: 'teacher_profile_update'
  end

  root to: "exams#index"
  resources :exams do
    resources :tests
    resources :records, only: [:new, :create, :edit, :update, :destroy]
  end

  resources :interviews, only: [:new, :create, :edit, :update]

  resources :units, only: :index

end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :room
end

app/models/club.rb
class Club < ActiveHash::Base
  self.data = [
    { id: 0, name: '---' },
    { id: 1, name: '陸上競技部' },
    { id: 2, name: 'サッカー部' },
    { id: 3, name: '野球部' },
    { id: 4, name: 'ハンドボール部' },
    { id: 5, name: 'テニス部' },
    { id: 6, name: 'ソフトテニス部' },
    { id: 7, name: 'バレーボール部' },
    { id: 8, name: 'バスケットボール部' },
    { id: 9, name: 'バドミントン部' },
    { id: 10, name: '卓球部' },
    { id: 11, name: '体操部' },
    { id: 12, name: '柔道部' },
    { id: 13, name: '剣道部' },
    { id: 14, name: '弓道部' },
    { id: 15, name: '水泳部' },
    { id: 16, name: '放送部' },
    { id: 17, name: '科学部' },
    { id: 18, name: '美術部' },
    { id: 19, name: '書道部' },
    { id: 20, name: '囲碁・棋道部' },
    { id: 21, name: '吹奏楽部' },
    { id: 22, name: '調理部' },
    { id: 23, name: '茶道部' },
    { id: 24, name: '合唱部' },
    { id: 25, name: '文芸部' },
    { id: 26, name: '演劇部' },
    { id: 27, name: '新聞部' },
    { id: 28, name: 'ダンス部' },
    { id: 29, name: '軽音楽部' },
    { id: 30, name: '写真部' }
  ]
end

app/models/exam.rb
class Exam < ApplicationRecord

  validates :name, presence: true
  
  belongs_to :teacher
  belongs_to :unit
  has_many :tests
  has_many :records
end

app/models/interview.rb
class Interview < ApplicationRecord

  validates :content, presence: true

  belongs_to :student
end

app/models/record.rb
class Record < ApplicationRecord

  validates :score, presence: true

  belongs_to :student
  belongs_to :exam
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :teacher
  belongs_to :student
  has_many :chats, dependent: :destroy
end

app/models/school_year.rb
class SchoolYear < ActiveHash::Base
  self.data = [
    { id: 0, name: '---' },
    { id: 1, name: '中学１年生' },
    { id: 2, name: '中学２年生' },
    { id: 3, name: '中学３年生' }
  ]
end

app/models/student.rb
class Student < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # パスワードの英数字混在を否定
  PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i.freeze
  validates_format_of :password, with: PASSWORD_REGEX, message: 'Include both letters and numbers', on: :create

  # 全角のひらがなor漢字を使用していないか検証
  with_options presence: true, format: { with: /\A[ぁ-んァ-ン一-龥]+\z/, message: 'Full-width characters' } do
    validates :first_name
    validates :last_name
  end

  # 全角のカタカナを使用していないか検証
  with_options presence: true, format: { with: /\A[\p{katakana}　ー－&&[^ -~｡-ﾟ]]+\z/, message: 'Full-width katakana characters' } do
    validates :first_name_kana
    validates :last_name_kana
  end

  with_options presence: true do
    validates :school_year_id
    validates :club_id
    validates :purpose
  end

  belongs_to_active_hash :school_year
  belongs_to_active_hash :club

  belongs_to :teacher
  has_many :records
  has_many :interviews
  has_many :rooms
  has_many :chats
end

app/models/subject.rb
class Subject < ApplicationRecord
  belongs_to :exam
  belongs_to :student
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # パスワードの英数字混在を否定
  PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i.freeze
  validates_format_of :password, with: PASSWORD_REGEX, message: 'Include both letters and numbers', on: :create

  # 全角のひらがなor漢字を使用していないか検証
  with_options presence: true, format: { with: /\A[ぁ-んァ-ン一-龥]+\z/, message: 'Full-width characters' } do
    validates :first_name
    validates :last_name
  end

  # 全角のカタカナを使用していないか検証
  with_options presence: true, format: { with: /\A[\p{katakana}　ー－&&[^ -~｡-ﾟ]]+\z/, message: 'Full-width katakana characters' } do
    validates :first_name_kana
    validates :last_name_kana
  end

  has_many :students
  has_many :exams
  has_many :rooms, dependent: :destroy
  has_many :chats, dependent: :destroy
end

app/models/test.rb
class Test < ApplicationRecord

  with_options presence: true do
    validates :question
    validates :answer
  end

  belongs_to :exam
  has_many_attached :images
  validates :images, length: { minimum: 0, maximum: 5, message: "は5枚以下にしてください" }
end

app/models/unit.rb
class Unit < ApplicationRecord
  validates :name, presence: true

  has_many :exams
  has_ancestry

  def self.unit_parent_array_create
    unit_parent_array = ['---']
    Unit.where(ancestry: nil).each do |parent|
      unit_parent_array << [parent.name, parent.id]
    end
    return unit_parent_array
  end
end

app/controllers/exams_controller.rb
class ExamsController < ApplicationController
  before_action :authenticate_teacher!, only: [:new, :create]
  before_action :set_exam, only: [:edit, :update, :destroy]

  def index
    @exams = Exam.order(created_at: :desc)
  end

  def new
    @exam = Exam.new
  end

  def create
    @exam = Exam.new(exam_params)
    if @exam.valid?
      @exam.save
    else
      render :new
    end
  end

  def show
    @exam = Exam.find(params[:id])
  end

  def edit
  end

  def update
    if @exam.valid?
      @exam.update(exam_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    if @exam.destroy
      redirect_to root_path
    else
      flash.now[:alert] = '試験削除に失敗しました'
      render :index
    end
  end

  private

  def exam_params
    params.require(:exam).permit(:name, :unit_id).merge(teacher_id: current_teacher.id)
  end

  def set_exam
    @exam = Exam.find(params[:id])
  end

end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/exams_helper.rb
module ExamsHelper
end

app/helpers/interviews_helper.rb
module InterviewsHelper
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/views/exams/_form.html.erb
<%= form_with(model: exam, local: true) do |f| %>
<% if exam.errors.any? %>
  <%= exam.errors.count %>件のエラー
  <% exam.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>
<div class="exam-content">
  <div class="field">
      <%= f.label :name %><br />
      <%= f.text_area :name, autofocus: true, autocomplete: "exam_name", required: true %>
    </div>

    <div id="unit_field">
      <%= f.label :unit_id %><br />
      <%= render partial: 'unit_form', locals: {units: Unit.roots, selected: exam.unit&.root&.id}%>
        <% if exam.unit&.parent %>
          <div>
            <%# 子カテゴリのフォーム %>
            <%= render partial: 'unit_form', locals: {units: exam.unit.parent.siblings, selected: exam.unit.parent.id }%>
            <div>
              <% if exam.unit %>
                <%# 孫カテゴリのフォーム %>
                <%= render partial: 'unit_form', locals: {units: exam.unit.siblings, selected: exam.unit.id }%>
              <% end %>
            </div>
          </div>
        <% end %>
    </div>

    <div class="actions">
      <%= f.submit "create", data: { disable_with: '作成中...' } %>
    </div>
  <% end %>
</div>

app/views/exams/_unit_form.html.erb
<%= collection_select :exam, :unit_id, units, :id, :name, {include_blank: "ーーーーー", selected: selected}, class: "unit-select-form", required: true %>

app/views/exams/create.html.erb
<%= render "shared/header" %>

<div class="top-contents-new">
  <div class="exams-index">
    <h1>試験作成に成功しました</h1>
    <%= link_to "試験一覧へ", root_path, class: "top-lists-btn" %>
  </div>
</diV>

app/views/exams/edit.html.erb
<%= render "shared/header" %>

<div class="top-contents-new">
  <%= link_to :root do %>
    <button class="back-btn">戻る</button>
  <% end %>
  <div class="exams-index">
    <h2>試験問題の更新する</h2>
  </div>
  <br>
  <div class="exams-lists">
    <%= render 'form', exam: @exam %>
  </div>
</div>

app/views/exams/index.html.erb
<%= render "shared/header" %>
<div class="top-lists">
  <%= link_to '試験作成', new_exam_path, class: "top-lists-btn" if teacher_signed_in?%>
  <%= link_to "生徒検索へ", students_index_path, class: "top-lists-btn" %>
</div>


<%# 生徒の今日の予定を表示させる %>


<div class="top-contents">
  <div class="exams-index">
    <h2>試験一覧</h2>
  </div>
  <ul class="exams-lists">
    <% @exams.each do |exam| %>
      <li class="exam-content">
        <% if teacher_signed_in? && exam.teacher_id == current_teacher.id %>
          <%= link_to "編集", edit_exam_path(exam), class: "exam-content-btn" %>
          <%= link_to "削除", exam_path(exam), method: :delete, data: { disable_with: '削除中...' }, data: {confirm: "試験を削除しますか？"}, class: "exam-content-btn" %>
        <% end %>
        <br>
        作成日：<%= exam.created_at.strftime("%Y年%m月%d日") %>
        <br>
        テスト作成者：<%= exam.teacher.first_name %>
        <br>
        <% if exam.records.find_by(student_id: current_student).present? %>
          <%= "あなたはこの試験を#{exam.records.find_by(student_id: current_student).created_at.strftime("%Y年%m月%d日")}に実施しました"%>
          結果：<%= exam.records.find_by(student_id: current_student).score %>点
          <br>
          <%= link_to "点数の編集", edit_exam_record_path(exam.id, exam.records.find_by(student_id: current_student).id) %>
          <%= link_to "点数の削除", exam_record_path(exam.id, exam.records.find_by(student_id: current_student).id), method: :delete, data: { disable_with: '削除中...' }, data: {confirm: "点数を削除しますか？"} %>
        <% elsif current_student.present? %>
          <%= link_to "試験結果を入力する", new_exam_record_path(exam) %>
        <% end %>
        <br>
        <%= link_to "受けた生徒一覧を表示", exam_path(exam), class: "exam-student-lists" if teacher_signed_in?%>
        <br>
        試験名：<%= exam.name %>
        <br>
        学年・教科：<%= exam.unit.root.name%>
        <br>
        大単元：<%= exam.unit.parent.name%>
        <br>
        小単元：<%= exam.unit.name%>
        <br>
        <% if teacher_signed_in? || student_signed_in? %>
          <%= link_to "問題一覧へ", exam_tests_path(exam), class: "exam-lists" %>
        <% else %>
          <h5>問題を実施するにはログインしてください</h5>
        <% end %>
      <% end %>
    </li>
  </ul>
</div>

app/views/exams/new.html.erb
<%= render "shared/header" %>

<div class="top-contents-new">
  <%= link_to :root do %>
    <button class="back-btn">戻る</button>
  <% end %>
  <div class="exams-index">
    <h2>試験問題の新規作成する</h2>
  </div>
  <br>
  <div class="exams-lists">
    <%= render 'form', exam: @exam %>
  </div>
</div>

app/views/exams/show.html.erb
<%= render "shared/header" %>

<div class="top-contents">
  <%= link_to :root do %>
    <button class="back-btn">戻る</button>
  <% end %>
  <div class="exams-index">
    <h3>試験名</h3>
    <%= @exam.name %>
  </div>
  <ul class="exams-lists">
    <br>
    <h3>この試験を受けた生徒一覧</h3>
    <% @exam.records.each do |record|%>
      <li class="exam-content">
        <%= record.student.school_year.name %><br>
        <%= record.student.first_name %><br>
        <%= record.score %>点<br>
        <%= record.created_at.strftime("%Y年%m月%d日")%>に実施しました<br>
        <br>
      </li>
    <% end %>
  </ul>
</div>